#!/usr/bin/env python3

import os
import requests

HEADER = """# This file is generated by $tflite2onnx/scripts/gen.py

from tflite2onnx.op.common import OpFactory


OP_NAMES = """

TAIL = """


def getSupportedOperators():
    opcs = list(OpFactory.registry.keys())
    opcs.sort()
    names = [OP_NAMES[opc] for opc in opcs]
    return names
"""


def getTypeNames():
    print("Downloading BuiltinOperator file...")
    url = 'https://raw.githubusercontent.com/jackwish/tflite/master/tflite/BuiltinOperator.py'
    r = requests.get(url)
    txt = r.content.decode('utf-8')
    lines = txt.split('\n')
    lines = [line for line in lines if '=' in line]
    types = [line.split('=')[0].strip() for line in lines]
    name_list = "[\n"
    for tname in types:
        name_list += "    '" + tname + "',\n"
    name_list += "]"
    return name_list


def main():
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    file_path = os.path.join(root_dir, 'tflite2onnx', 'tflops.py')
    if os.path.exists(file_path):
        print("Removing existing file %s", file_path)
        os.unlink(file_path)
    print("Writing file %s", file_path)
    with open(file_path, 'w') as f:
        f.write(HEADER)
        f.write(getTypeNames())
        f.write(TAIL)
    print("All done!")


if __name__ == '__main__':
    main()
